version: '3.8'
services: 
 java-maven-app: 
  image: tomiwa97/docker_app:1.1.3-37
  ports: 
   - 8080:8080
  postgres:
   image: postgres:13-alpine
   ports:
    - 5432:5432
   environment:
    - POSTGRES_PASSWORD:my-pwd
